name: Pack and Publish NuGet Packages

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  
jobs:
  pack-and-publish:
    runs-on: ubuntu-latest  # Or your preferred runner
    
    env:
       CURRENT_VERSION: $ENGINE_VERSION
       
    steps:
      - uses: actions/checkout@v4  # Checkout code from repository

      - name: Use NuGet CLI
        uses: nuget/setup-nuget@v2  # Install the NuGet CLI

      - name: Use Dotnet CLI
        uses: actions/setup-dotnet@v4 # Install the Dotnet CLI
        with:
          dotnet-version: 8
          
      - name: Restore dependencies
        run: nuget restore ./GameEngine.sln  # Replace with your solution file path
    
      - name: Pack GameEngine
        run: |
          dotnet pack ./GameEngine/GameEngine.csproj /p:PackageVersion=$CURRENT_VERSION -o ./nuget_packages

      - name: Pack GameEngine.Core
        run: |
          dotnet pack ./GameEngine.Core/GameEngine.Core.csproj /p:PackageVersion=$CURRENT_VERSION -o ./nuget_packages

      - name: Pack GraphicsEngine
        run: |
          dotnet pack ./GraphicsEngine/GraphicsEngine.csproj /p:PackageVersion=$CURRENT_VERSION -o ./nuget_packages

      - name: Pack PhysicsEngine
        run: |
          dotnet pack ./PhysicsEngine/PhysicsEngine.csproj /p:PackageVersion=$CURRENT_VERSION -o ./nuget_packages

      - name: Pack SoundEngine
        run: |
          dotnet pack ./SoundEngine/SoundEngine.csproj /p:PackageVersion=$CURRENT_VERSION -o ./nuget_packages

      - name: Pack InputEngine
        run: |
          dotnet pack ./InputEngine/InputEngine.csproj /p:PackageVersion=$CURRENT_VERSION -o ./nuget_packages

      - name: Publish NuGet packages
        run: |
          nuget push ./nuget_packages/YonatanZ.GameEngine.$CURRENT_VERSION.nupkg ${{ secrets.NUGET_API_KEY }} -src https://www.nuget.org/
          nuget push ./nuget_packages/YonatanZ.GameEngine.Core.$CURRENT_VERSION.nupkg ${{ secrets.NUGET_API_KEY }} -src https://www.nuget.org/
          nuget push ./nuget_packages/YonatanZ.GraphicsEngine.$CURRENT_VERSION.nupkg ${{ secrets.NUGET_API_KEY }} -src https://www.nuget.org/
          nuget push ./nuget_packages/YonatanZ.InputEngine.$CURRENT_VERSION.nupkg ${{ secrets.NUGET_API_KEY }} -src https://www.nuget.org/
          nuget push ./nuget_packages/YonatanZ.PhysicsEngine.$CURRENT_VERSION.nupkg ${{ secrets.NUGET_API_KEY }} -src https://www.nuget.org/
          nuget push ./nuget_packages/YonatanZ.SoundEngine.$CURRENT_VERSION.nupkg ${{ secrets.NUGET_API_KEY }} -src https://www.nuget.org/
